<?php

session_start();

$_SESSION['lang'] = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);
$lang = $_SESSION['lang'];

function translatePg() {
    $varArray = [
        "pt" => ["title" => "Sistema de Gerenciamento de Projetos",
            "text_login" => "Preencha os campos abaixo para acessar o sistema.",
            "text_caduser" => "Preencha os campos abaixo para efetuar o cadastro.",
            "text_cadproj" => "Informe os dados do Projeto.",
            "text_cadtask" => "Informe os dados da Tarefa.",
            "text_search" => "Pesquisar Projetos",
            "text_coord" => "Coordenador do Projeto",
            "text_progress" => "Concluído",
            "pholder_email" => "Informe o e-mail",
            "pholder_projname" => "Insira o nome do projeto",
            "pholder_username" => "Insira o nome do user",
            "pholder_taskname" => "Insira o nome da tarefa",
            "pholder_projdesc" => "Descrição do projeto",
            "pholder_projcat" => "Selecione a categoria",
            "pholder_taskresp" => "Selecione o responsável",
            "pholder_pass" => "Informe a senha",
            "pholder_confpass" => "Confirme a senha",
            "pholder_phone" => "Telefone(apenas números)",
            "pholder_projstart" => "Data de Início",
            "pholder_projend" => "Data de Fim",
            "btn_register" => "Cadastrar",
            "btn_login" => "Acessar Sistema",
            "btn_options" => "Opções",
            "btn_search" => "Buscar",
            "btn_add" => "Adicionar",
            "btn_project" => "Criar Novo Projeto",
            "btn_deltask" => "Excluir Tarefa",
            "menu_item1" => "Meus Projetos",
            "menu_item2" => "Minhas Tarefas",
            "menu_item3" => "Sair",
            "card_user" => "Dados do Usuário",
            "card_projects" => "Projetos",
            "card_tasks" => "Tarefas",
            "card_contacts" => "Contatos",
            "card_files" => "Arquivos",
            "tblProj_col1" => "Nome do Projeto",
            "tblProj_col2" => "Data de Início",
            "tblProj_col3" => "Data de Fim",
            "tblProj_col4" => "Categoria",
            "tblProj_col5" => "Tarefas",
            "days_remain" => "dias restantes",
            "card_team" => "Integrantes",
            "card_email_resp" => "Enviar e-mail ao responsável",
            "card_email_adm" => "Enviar e-mail ao coordenador",
            "text_nomembers" => "Não há integrantes",
            "text_taskfinished" => "Finalizada",
            "text_tasknofinished" => "Incompleta",
            "tblTask_col1" => "Nome da Tarefa",
            "tblTask_col2" => "Data Registrada",
            "tblTask_col3" => "Responsável",
            "tblTask_col4" => "Status",
            "btn_email" => "Enviar E-mail",
            "btn_finish" => "Finalizar",
            "btn_reopen" => "Reabrir",
            "btn_send" => "Enviar",
            "card_addmember" => "Adicionar Integrante",
            "text_addmember" => "Insira o e-mail do usuário para integrá-lo ao projeto"
        ],
        
        "en" => ["title" => "Project Management System",
            "text_login" => "Please, fill the informations bellow to access the system.",
            "text_caduser" => "Please, fill the informations bellow to register your account.",
            "text_cadproj" => "Fill the fields bellow with the project informations.",
            "text_cadtask" => "Fill the fields bellow with the task data.",
            "pholder_email" => "E-mail",
            "pholder_projname" => "Project Name",
            "pholder_username" => "User Name",
            "pholder_taskname" => "Task Name",
            "pholder_projdesc" => "Description",
            "pholder_projcat" => "Choose a category",
            "pholder_taskresp" => "Select the responsible member",
            "pholder_pass" => "Password",
            "pholder_confpass" => "Confirm Password",
            "pholder_phone" => "Phone number",
            "pholder_projstart" => "Start date",
            "pholder_projend" => "End date",
            "btn_register" => "Register",
            "btn_add" => "Add",
            "btn_login" => "Log in",
            "menu_item1" => "My Projects",
            "menu_item2" => "My Tasks",
            "menu_item3" => "LogOut",
            "btn_search" => "Search",
            "btn_project" => "Create New Project",
            "btn_deltask" => "Delete Task",
            "card_user" => "User Data",
            "card_files" => "Files",
            "card_projects" => "Projects",
            "card_tasks" => "Tasks",
            "card_email_resp" => "Send an e-mail to responsible",
            "card_email_adm" => "Send an e-mail to coordinator",
            "card_contacts" => "Contacts",
            "btn_options" => "Options",
            "text_search" => "Search for Projects",
            "tblProj_col1" => "Project Name",
            "tblProj_col2" => "Start",
            "tblProj_col3" => "End",
            "tblProj_col4" => "Category",
            "tblProj_col5" => "Tasks",
            "text_coord" => "Manager",
            "text_progress" => "Progress",
            "days_remain" => "days remaining",
            "card_team" => "Team Members",
            "text_nomembers" => "No members",
            "text_taskfinished" => "Completed",
            "text_tasknofinished" => "Pendent",
            "tblTask_col1" => "Task Name",
            "tblTask_col2" => "Date",
            "tblTask_col3" => "Responsible",
            "tblTask_col4" => "Status",
            "btn_email" => "Send E-mail",
            "btn_finish" => "Finish",
            "btn_reopen" => "Reopen",
            "btn_send" => "Send",
            "card_addmember" => "Add member",
            "text_addmember" => "Insert a active user e-mail address to include in team"
        ]
    ];

    return $varArray;
}
?>		


<?php

/* $ip=$_SERVER['REMOTE_ADDR'];
  $xml = simplexml_load_file("http://www.geoplugin.net/xml.gp?ip=$ip");
  echo $xml->geoplugin_countryName . " - " . $ip;
 */
?>	